### ISSUE TITLE
react-jsonschema-form-material-ui@1.0.95: The engine "node" is incompatible with this module. Expected version "8.9.4".

### ISSUE THREAD

**Issue by vtharmalingam** [vip-git/react-jsonschema-form-material-ui#1]
Hi,

Can you please educate me why this cannot work with node@11.*?
The error mentioned during "yarn add xxxx" caused a big head-ache. Finally, I had to drop this package and move on.

Thanks,
Tharma

**Comment by vip-git** [comment]
Hi @vtharmalingam  - can you please provide the steps on how you end up with this error ?

It seems like one of the dependencies is not compatible with node 11.x .

Looking forward to your reply.

Thanks,
V
