### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by adamhooper** [vip-git/react-jsonschema-form-material-ui#223]
Steps to take:

1. `npm init` in a fresh directory
2. `npm install --save react@16.13.0 react-dom@16.13.0 @material-ui/core`
3. `npm install --save react-jsonschema-form-material-ui`

Expected results: a clean install

Actual results: two copies of React will be bundled: the one I installed, and the one react-jsonschema-form-material-ui depends on.

*Solution*

The following should be `peerDependencies` and `devDependencies`, not `dependencies`:

* `react@^16.13.1`
* `react-dom@^16.13.1`

The reason React should not be a dependency is: it prevents users from relying on two libraries that depend on different versions of React. (And any two libraries, at any given moment, typically _do_ depend on different versions of React.)

This would technically force a major version bump: users who installed `react-jsonschema-form-material-ui` without ever installing `react` will lose `react` if they upgrade `react-jsonschema-form-material-ui` to a version that doesn't depend on `react`. But in practice, zero users have probably done so.

And while we're at it, here are more fixes that help integrate this library with the rest of a project:

The following should be `devDependencies`, not `dependencies`:

* `react-hot-loader@4.12.10`
* `typeface-roboto@0.0.75`
* `express`
* `body-parser`
* `cross-env`
* `emotion`

Rationale: exported code does not require them.

These three should be `peerDependencies` and `devDependencies`, not `dependencies`. Also, versions should begin with `^`:

* `@material-ui/core@^4.9.7`
* `@material-ui/icons@^4.9.1`
* `@material-ui/pickers@^3.2.10`

Rationale: Isn't react-jsonschema-form-material-ui meant to be "Bring Your Own material-ui"? Hard-coded dependency versions force users to require duplicate copies of material-ui: their own version, plus the version required by `react-jsonschema-form-material-ui`. This can create errors in calling code when users aren't aware they're depending upon two different versions of `material-ui`.

**Changing material-ui to peerDependencies would require a major version bump**, as the install instructions would change. Instead of asking users to `npm install --save react-jsonschema-form-material-ui`, they would need to `npm install --save react-jsonschema-form-material-ui @material-ui/core @material-ui/icons @material-ui/pickers`. (This same command happens to be the upgrade command that accompanies the major version bump.)

And finally, this should probably be a `dependency`, not a `peerDependency`:

* `immutability-helper` (it's already a dependency)

**Comment by vip-git** [comment]
Hi 👋 @adamhooper 

Thanks for your issue there - it does open up certain refractors.

The plan moving ahead is also to “bring your own custom components” in at one point and there is a refactor in progress as we speak to modularise react json forms schema . 

What I suggest for now if you can get the recommended changes in a small PR we can merge it. 

Later there will be a follow up on getting dependencies out of react json form schéma and being added based on a config which also helps in bundling of the library And on top this gives you full flexibility to add you new components to already existing set of components within react json form schema.

Looking forward to your PR when that’s ready.

Thanks - V
