### ISSUE TITLE
Invalid hook call.

### ISSUE THREAD

**Issue by amitudale2730** [vip-git/react-jsonschema-form-material-ui#233]
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Comment by amitudale2730** [comment]
used         <MaterialJsonSchemaForm
                  schema={schema}
                  formData={formData}
            />

**Comment by amitudale2730** [comment]
@vip-git - Can you please help me out with this one

**Comment by andrechavesg** [comment]
Same problem here

**Comment by vip-git** [comment]
Hi @amitudale2730 and @andrechavesg 

can i know the version of react and react-dom you are using ?

```
You might have mismatching versions of React and the renderer (such as React DOM)
```

Looking forward to your reply.

Thanks - V

**Comment by vip-git** [comment]
Closing this issue as there has been no reply on it.
