### ISSUE TITLE
Components not re-render when data from schema is changed

### ISSUE THREAD

**Issue by dragos199993** [vip-git/react-jsonschema-form-material-ui#345]
Hello,
We used **'react-jsonschema-form-material-ui'** and we discovered that the package is applying some sort of memo on the data inside a json schema property.

If the number of sections are changed, the sections that are missing or added are correctly displayed.
But if the sections remains and only the content inside gets changed, the custom component isn't rerended.
We tested and we exclude other possibilities. Somewhere inside the package there is a verification that skips the rerender if the key is not changed.

NOTE: This is related to https://github.com/vip-git/react-jsonschema-form-material-ui/pull/344 as we need to display static data on a section.

**Comment by szabi7** [comment]
Same here!

**Comment by vip-git** [comment]
Hi @dragos199993 - Thanks for the issue there.

Do you have a example for me - where you are facing this like steps or example `formSchema`, `formData` and `uiSchema` will help in resolving this better.

Looking forward to your reply.

Thanks - V

**Comment by vip-git** [comment]
Hi @dragos199993  - Are you able to try and confirm if you are still facing this issue after updating to [Version 2.1.10](https://github.com/vip-git/react-jsonschema-form-material-ui/releases/tag/2.1.10) ?

**Comment by dragos199993** [comment]
Hi, actually I managed to fix this by trigger a render when my schema changes.
I passed a key={} that changes when I need to update the schema. It's a workaround but it works, so no need to take any action here.
You can consider this as solved.

**Comment by vip-git** [comment]
Glad it was resolved for you @dragos199993 - I have closed #344 as well which was resolved part of [Version 2.1.11](https://github.com/vip-git/react-jsonschema-form-material-ui/releases/tag/2.1.11)

In case there are future ideas to be implemented give me a shout or send a PR in when necessary .

Thanks for creating this issue 👍
