### ISSUE TITLE
Facing issue while using with react router or when doing toggle visibility of component

### ISSUE THREAD

**Issue by hitendramalviya** [vip-git/react-jsonschema-form-material-ui#394]
First, let me appreciate the efforts on such a nice use case development. Now come to the issue we are facing while using this library in our project. It works fine as expected till remain on same form while using along with react router, once we navigate to other route & comes back it starts breaking. I don't find a better way to explain the issue, so I created codesandbox to reproduce the case.

https://codesandbox.io/s/reproduce-memory-leak-react-jsonschema-form-material-ui-fb4r2?file=/src/App.js

To see the issue in action, you can check the navigation title:

- Normal case (working till I move on a different route, will not work after coming back from other route)
- Here also you can see issue
- Normal input working as expected

After navigating try editing the field, you will see warning in console saying that 

`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application.`

![image](https://user-images.githubusercontent.com/5709606/126505536-170fa903-3033-4e48-b487-45e462a48a12.png)

And field's value will not updated.

At the same time, the same code block on a normal text field works as expected. (Navigate on `Normal input working as expected` to see that)

**Comment by vip-git** [comment]
Hi @hitendramalviya  - Thanks for raising this issue.

I will try to look into your sandbox and see if i can have it replicated.

Although there was already a similar issue raised earlier where the [solution was posted ](https://github.com/vip-git/react-jsonschema-form-material-ui/issues/345#issuecomment-721093247) .

Are you able to check once if this resolves your issue ?

I will get back to you as well with the warning you seem to see if that can be dealt with.

Thanks - V

**Comment by vip-git** [comment]
Hi @hitendramalviya - I had a look at your sandbox.

The solution for your case is even simpler. 

You seem to be getting that warning as you don't have `onChange` prop defined

```
onChange={({ formData }) => setFormData(formData)}
```

Full basic example as mentioned [here](https://github.com/vip-git/react-jsonschema-form-material-ui#basic-example-usage).

I hope this resolves your issue. Feel free to reopen this incase it does not.

**Comment by hitendramalviya** [comment]
Dear @vip-git 

Thanks a lot for the response, please consider my below observation about the issue again:
- `key` is a reserved property used to maintain uniqueness of record while rendering an array of items. https://reactjs.org/docs/lists-and-keys.html I don't feel we are required to define that in our case in sandbox.
- I have updated the sandbox, the issue still persist there, I removed react router still it is a problem, you can try the sandbox again:
- https://codesandbox.io/s/reproduce-memory-leak-react-jsonschema-form-material-ui-forked-p9h3t?file=/src/App.js
- Open sandbox, click toggle button to see editor
- Then enter anything on that
- Then click on toggle again
- Now again try entering, and observe that, not able to enter anything further in any field there.

**Comment by vip-git** [comment]
Hi @hitendramalviya - Your updated example is helpful. 

This looks to me more a issue with react loosing the reference on input created on mount and unmount.

But if you maintain the reference by not unmounting the component (not removing and inserting back in dom) by just using CSS your issue is resolved giving you similar effect.

This is the updated working example
- https://codesandbox.io/s/reproduce-memory-leak-react-jsonschema-form-material-ui-forked-p2k8l?file=/src/App.js

See if this helps - i can look into the reference issue if you think css display solves your issue or not.

Thanks - V

**Comment by hitendramalviya** [comment]
Hello @vip-git 

CSS display, I already thought of implementing, but in our case we are rendering `MaterialJsonSchemaForm` inside a`temporary` Drawer which is owned by material ui, so they are fully unmounting child.

I did a different workaround to make it working inside the Drawer, after I reviewed source code on your repo. I am able to apply a workaround by fooling React.memo by updating schema object on toggle happening:
```
const schema = useMemo(() => ({ ...givenSchema, id: Date.now() }), [toggleProp]);
return <MaterialJsonSchemaForm schema={schema} {...rest} />;
```

If I get chance, I will love to contribute & send a PR on your repo to fix this issue.

Regards,
Hitendra

**Comment by vip-git** [comment]
Great @hitendramalviya 🙂.

Glad you managed to have it fixed. If you have time please do send a PR through .

I would be finalizing version 3 in coming weeks and releasing the beta out with latest version of material UI 5 beta next week.

It would be great to have this patch on memo available part of version 3-beta.x 

Thanks for your inputs so far - V
