### ISSUE TITLE
Unexpected token (5889:15)

### ISSUE THREAD

**Issue by silencej** [vip-git/react-jsonschema-form-material-ui#411]
> ./node_modules/react-jsonschema-form-material-ui/dist/bundle.js 5889:15
> Module parse failed: Unexpected token (5889:15)
> File was processed with these loaders:
>  * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
>    } catch (e) {
>      return { ...t,
>       title: t?.title
>      };
>    }

My dependencies:

``` json
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-jsonschema-form-material-ui": "^3.0.0-beta.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
```

**Comment by vip-git** [comment]
Hi @silencej ,

Are you using typescript in your project ?

You would need to set the target to `es6` in `tsconfig.json`

```

{
    "target": "ES6",
    // ...
}

```

**Comment by vip-git** [comment]
Hi @silencej  -  Can you try `3.0.0-beta.3` as well to see if you still see the issue ?

Thanks - V

**Comment by silencej** [comment]
@vip-git I confirm that the issue is gone in beta.3.   Thanks for fixing this!

**Comment by vip-git** [comment]
Thanks for raising this as well @silencej .

**Comment by AlexThurston** [comment]
It looks like this is a problem in `3.0.0-rc.5`
