### ISSUE TITLE
MultiSelect field ignores disabled property

### ISSUE THREAD

**Issue by tijpenga** [vip-git/react-jsonschema-form-material-ui#69]
When I add `"ui:options": { "disabled": true }` to the uiSchema of a `"ui:widget": "material-multiselect"` field, the MultiSelect field is not disabled.

How to reproduce:
1. Go to https://react-jsonschema-form-material.herokuapp.com/
2. Add `"ui:options": { "disabled": true }` to the `selectTest` field in the uiSchema
3. The field is not disabled

**Comment by vip-git** [comment]
Hi @tijpenga  -  Thanks for reporting the bug.

This issue has now been fixed as part of version `1.0.103` .

Thanks - V
