### ISSUE TITLE
Form validations are not working

### ISSUE THREAD

**Issue by alkeshshahrspl** [vip-git/react-jsonschema-form-material-ui#96]
required fields and other form validations are not working.

Please guide on form validations

**Comment by vip-git** [comment]
Hi @alkeshshahrspl ,

Thanks for your issue - validations were working just were not documented. 

Now they are documented [here](https://react-json-schema.app/validations).

There was a new release made [2.2.0](https://github.com/vip-git/react-jsonschema-form-material-ui/releases/tag/2.2.0) which also supports [custom validations now](https://react-json-schema.app/validations/custom-validation).

Thanks - V
